echo "Test Deez Nutz"
echo "My Buttz"
echo "Topsy Krutz"
echo "More smoke"
echo "Yo doke"
echo "Shoke"
echo "Let's Crack"
echo "no paddle just deez nutz"
echo "row row row, bitch"
echo "gently down this scrote"
echo "Merrily Merrily Merrily"
echo "Gently down the streamz"
